Same auctions, different plays ğŸ¤”

Ah, it's probably because `generate_fake_data.py` uses the same "canned calls".  Probably time to do something about that.
